/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_xchen_HashKV */

#ifndef _Included_com_xchen_HashKV
#define _Included_com_xchen_HashKV
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_xchen_HashKV
 * Method:    openDiskManager
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_xchen_HashKV_openDiskManager
  (JNIEnv *, jobject);

/*
 * Class:     com_xchen_HashKV
 * Method:    open
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_xchen_HashKV_open
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_xchen_HashKV
 * Method:    close
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_xchen_HashKV_close
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     com_xchen_HashKV
 * Method:    put
 * Signature: (J[B[B)Z
 */
JNIEXPORT jboolean JNICALL Java_com_xchen_HashKV_put
  (JNIEnv *, jobject, jlong, jbyteArray, jbyteArray);

/*
 * Class:     com_xchen_HashKV
 * Method:    delete
 * Signature: (J[B)Z
 */
JNIEXPORT jboolean JNICALL Java_com_xchen_HashKV_delete
  (JNIEnv *, jobject, jlong, jbyteArray);

/*
 * Class:     com_xchen_HashKV
 * Method:    get
 * Signature: (J[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_xchen_HashKV_get
  (JNIEnv *, jobject, jlong, jbyteArray);

/*
 * Class:     com_xchen_HashKV
 * Method:    scan
 * Signature: (J[BJ)Lcom/xchen/HashKV/KVPair;
 */
JNIEXPORT jobject JNICALL Java_com_xchen_HashKV_scan
  (JNIEnv *, jobject, jlong, jbyteArray, jlong);

#ifdef __cplusplus
}
#endif
#endif
